#include<bits/stdc++.h>
using namespace std;
int t,i,j,n;
int main()
{
    freopen("sticks.in","r",stdin);
    freopen("sticks.out","w",stdout);
    cin>>t;
    for(i=1;i<=t;i++)
    {
        cin>>n;
        if(n==1)
        {
            cout<<-1<<endl;
            continue;
        }
        if(n==2)
        {
            cout<<1<<endl;
            continue;
        }
        if(n==3)
        {
            cout<<7<<endl;
            continue;
        }
        if(n==4)
        {
            cout<<4<<endl;
            continue;
        }
        if(n==5)
        {
            cout<<2<<endl;
            continue;
        }
        if(n==6)
        {
            cout<<6<<endl;
            continue;
        }
        if(n%7==0)
        {
            for(j=1;j<=n/7;j++)
                cout<<8;
            cout<<endl;
        }
        if(n%7==1)
        {
            cout<<1<<0;
            for(j=1;j<=(n-8)/7;j++)
                cout<<8;
            cout<<endl;
        }
        if(n%7==2)
        {
            cout<<1;
            for(j=1;j<=(n-2)/7;j++)
                cout<<8;
            cout<<endl;
        }
        if(n%7==3)
        {
            cout<<2<<2;
            for(j=1;j<=(n-10)/7;j++)
                cout<<8;
            cout<<endl;
        }
        if(n%7==4)
        {
            cout<<2<<0;
            for(j=1;j<=(n-11)/7;j++)
                cout<<8;
            cout<<endl;
        }
        if(n%7==5)
        {
            cout<<2;
            for(j=1;j<=(n-5)/7;j++)
                cout<<8;
            cout<<endl;
        }
        if(n%7==6)
        {
            cout<<6;
            for(j=1;j<=(n-6)/7;j++)
                cout<<8;
            cout<<endl;
        }
    }
    fclose(stdin);
    fclose(stdout);
    return 0;
}