#include<bits/stdc++.h>
using namespace std;
int t,n,m,k,x,y,d,sum=0;
char ch[1010][1010];
int main()
{
    freopen("explore.in","r",stdin);
    freopen("explore.out","w",stdout);
    cin>>t;
    while(t--)
    {
        cin>>n>>m>>k;
        cin>>x>>y>>d;
        for(int i=1;i<=n;i++)
        {
            for(int j=1;j<=m;j++)
            {
                cin>>ch[i][j];
            }
        }
        sum=0;
        for(int i=1;;i++)
        {
            if(i==1)
            {
                if(d==0)
                {
                    if(ch[x][y+1]=='.')
                    {
                        y++;
                        k--;
                    }
                    else
                    {
                        k--;
                        d++;
                    }
                    if(k==0)
                    {
                        cout<<sum+1<<endl;
                        break;
                    }
                }
                if(d==1)
                {
                    if(ch[x+1][y]=='.')
                    {
                        x++;
                        k--;
                    }
                    else
                    {
                        k--;
                        d++;
                    }
                    if(k==0)
                    {
                        cout<<sum+1<<endl;
                        break;
                    }
                }
                if(d==2)
                {
                    if(ch[x][y-1]=='.')
                    {
                        y--;
                        k--;
                    }
                    else
                    {
                        k--;
                        d++;
                    }
                    if(k==0)
                    {
                        cout<<sum+1<<endl;
                        break;
                    }
                }
                if(d==3)
                {
                    if(ch[x-1][y]=='.')
                    {
                        x--;
                        k--;
                    }
                    else
                    {
                        k--;
                        d=0;
                    }
                    if(k==0)
                    {
                        cout<<sum+1<<endl;
                        break;
                    }
                }
            }
            if(d==0)
            {
                if(ch[x][y+1]=='.')
                {
                    y++;
                    sum++;
                    k--;
                }
                else
                {
                    k--;
                    d++;
                }
                if(k==0)
                {
                    cout<<sum+1<<endl;
                    break;
                }
            }
            if(d==1)
            {
                if(ch[x+1][y]=='.')
                {
                    x++;
                    sum++;
                    k--;
                }
                else
                {
                    k--;
                    d++;
                }
                if(k==0)
                {
                    cout<<sum+1<<endl;
                    break;
                }
            }
            if(d==2)
            {
                if(ch[x][y-1]=='.')
                {
                    y--;
                    sum++;
                    k--;
                }
                else
                {
                    k--;
                    d++;
                }
                if(k==0)
                {
                    cout<<sum+1<<endl;
                    break;
                }
            }
            if(d==3)
            {
                if(ch[x-1][y]=='.')
                {
                    x--;
                    sum++;
                    k--;
                }
                else
                {
                    k--;
                    d=0;
                }
                if(k==0)
                {
                    cout<<sum+1<<endl;
                    break;
                }
            }
        }
    }
}

