#include<bits/stdc++.h>
using namespace std;

long long T,c,n,m,k,x,d,l,y,com=100,ans;
int a[1010][1010];
string s;

int main(){
    freopen("explore1.in","r",stdin);
    freopen("explore.out","w",stdout);
    cin>>T;
    while(T>0){
        cin>>n>>m>>k;
        cin>>x>>y>>d;
        for(int i=1;i<=n;i++){
            cin>>s;
            for(int j=1;j<=m;j++){
                if(s[j-1]=='x'){
                    a[i][j]==0;
                }else if(s[j-1]=='.'){
                    a[i][j]==1;
                }
            }
        }
        while(k>=0){
            if(a[x][y+1]==1){
                if(d==0){
                    c=0;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==1){
                    c=3;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==2){
                    c=2;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==3){
                    c=1;
                    if(c<com){
                        com=c;
                    }
                }
            }
            if(a[x+1][y]==1){
                if(d==0){
                    c=1;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==1){
                    c=0;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==2){
                    c=3;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==3){
                    c=2;
                    if(c<com){
                        com=c;
                    }
                }
            }
            if(a[x][y-1]==1){
                if(d==0){
                    c=2;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==1){
                    c=1;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==2){
                    c=0;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==3){
                    c=3;
                    if(c<com){
                        com=c;
                    }
                }
            }
            if(a[x-1][y]==1){
                if(d==0){
                    c=3;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==1){
                    c=2;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==2){
                    c=1;
                    if(c<com){
                        com=c;
                    }
                }
                if(d==3){
                    c=0;
                    if(c<com){
                        com=c;
                    }
                }
            }
            for(int i=1;i<=com;i++){
                l=(d+1)%4;
            }
            if(l==0){
                k-=com+1;
                if(k>=0){
                    ans++;
                }else{
                    break;
                }
                y=y+1;
            }
            if(l==1){
                k-=com+1;
                if(k>=0){
                    ans++;
                }else{
                    break;
                }
                x=x+1;
            }
            if(l==2){
                k-=com+1;
                if(k>=0){
                    ans++;
                }else{
                    break;
                }
                y=y-1;
            }
            if(l==3){
                k-=com+1;
                if(k>=0){
                    ans++;
                }else{
                    break;
                }
                x=x-1;
            }
        }
        cout<<ans<<endl;
        T--;
    }
    return 0;
}