#include <bits/stdc++.h>
using namespace std;
char b[100];
bool s[52],c[52],h[52],d[52];
int n,cnt;
int main(){
    freopen("poker.in","r",stdin);
    freopen("poker.out","w",stdout);
    cin>>n;
    for(int i=1;i<=n;i++){
        cin>>b;
        if(b[0]=='S'){
           if(b[1]=='A')
            {cnt++;
              if(s[1]==1){
                cnt--;
              }
              s[1]=1;continue;
            }
           if(b[1]=='2')
            {cnt++;
              if(s[2]==1){
                cnt--;
              }
              s[2]=1;continue;
            }
           if(b[1]=='3')
            {cnt++;
              if(s[3]==1){
                cnt--;
              }
              s[3]=1;continue;
            }
           if(b[1]=='4')
            {cnt++;
              if(s[4]==1){
                cnt--;
              }
              s[4]=1;continue;
            }
           if(b[1]=='5')
            {cnt++;
              if(s[5]==1){
                cnt--;
              }
              s[5]=1;continue;
            }
           if(b[1]=='6')
            {cnt++;
              if(s[6]==1){
                cnt--;
              }
              s[6]=1;continue;
            }
           if(b[1]=='7')
            {cnt++;
              if(s[7]==1){
                cnt--;
              }
              s[7]=1;continue;
            }
           if(b[1]=='8')
            {cnt++;
              if(s[8]==1){
                cnt--;
              }
              s[8]=1;continue;
            }
           if(b[1]=='9')
            {cnt++;
              if(s[9]==1){
                cnt--;
              }
              s[9]=1;continue;
            }
           if(b[1]=='T')
            {cnt++;
              if(s[10]==1){
                cnt--;
              }
              s[10]=1;continue;
            }
           if(b[1]=='J')
            {cnt++;
              if(s[11]==1){
                cnt--;
              }
              s[11]=1;continue;
            }
           if(b[1]=='Q')
            {cnt++;
              if(s[12]==1){
                cnt--;
              }
              s[12]=1;continue;
            }
           if(b[1]=='K')
            {cnt++;
              if(s[13]==1){
                cnt--;
              }
              s[13]=1;continue;
            }
        }
        if(b[0]=='H'){
           if(b[1]=='A')
            {cnt++;
              if(h[1]==1){
                cnt--;
              }
              h[1]=1;continue;
            }
           if(b[1]=='2')
            {cnt++;
              if(h[2]==1){
                cnt--;
              }
              h[2]=1;continue;
            }
           if(b[1]=='3')
            {cnt++;
              if(h[3]==1){
                cnt--;
              }
              h[3]=1;continue;
            }
           if(b[1]=='4')
            {cnt++;
              if(h[4]==1){
                cnt--;
              }
              h[4]=1;continue;
            }
           if(b[1]=='5')
            {cnt++;
              if(h[5]==1){
                cnt--;
              }
              h[5]=1;continue;
            }
           if(b[1]=='6')
            {cnt++;
              if(h[6]==1){
                cnt--;
              }
              h[6]=1;continue;
            }
           if(b[1]=='7')
            {cnt++;
              if(h[7]==1){
                cnt--;
              }
              h[7]=1;continue;
            }
           if(b[1]=='8')
            {cnt++;
              if(h[8]==1){
                cnt--;
              }
              h[8]=1;continue;
            }
           if(b[1]=='9')
            {cnt++;
              if(h[9]==1){
                cnt--;
              }
              h[9]=1;continue;
            }
           if(b[1]=='T')
            {cnt++;
              if(h[10]==1){
                cnt--;
              }
              h[10]=1;continue;
            }
           if(b[1]=='J')
            {cnt++;
              if(h[11]==1){
                cnt--;
              }
              h[11]=1;continue;
            }
           if(b[1]=='Q')
            {cnt++;
              if(h[12]==1){
                cnt--;
              }
              h[12]=1;continue;
            }
           if(b[1]=='K')
            {cnt++;
              if(h[13]==1){
                cnt--;
              }
              h[13]=1;continue;
            }
        }
        if(b[0]=='C'){
           if(b[1]=='A')
            {cnt++;
              if(c[1]==1){
                cnt--;
              }
              c[1]=1;continue;
            }
           if(b[1]=='2')
            {cnt++;
              if(c[2]==1){
                cnt--;
              }
              c[2]=1;continue;
            }
           if(b[1]=='3')
            {cnt++;
              if(c[3]==1){
                cnt--;
              }
              c[3]=1;continue;
            }
           if(b[1]=='4')
            {cnt++;
              if(c[4]==1){
                cnt--;
              }
              c[4]=1;continue;
            }
           if(b[1]=='5')
            {cnt++;
              if(c[5]==1){
                cnt--;
              }
              c[5]=1;continue;
            }
           if(b[1]=='6')
            {cnt++;
              if(c[6]==1){
                cnt--;
              }
              c[6]=1;continue;
            }
           if(b[1]=='7')
            {cnt++;
              if(c[7]==1){
                cnt--;
              }
              c[7]=1;continue;
            }
           if(b[1]=='8')
            {cnt++;
              if(c[8]==1){
                cnt--;
              }
              c[8]=1;continue;
            }
           if(b[1]=='9')
            {cnt++;
              if(c[9]==1){
                cnt--;
              }
              c[9]=1;continue;
            }
           if(b[1]=='T')
            {cnt++;
              if(c[10]==1){
                cnt--;
              }
              c[10]=1;continue;
            }
           if(b[1]=='J')
            {cnt++;
              if(c[11]==1){
                cnt--;
              }
              c[11]=1;continue;
            }
           if(b[1]=='Q')
            {cnt++;
              if(c[12]==1){
                cnt--;
              }
              c[12]=1;continue;
            }
           if(b[1]=='K')
            {cnt++;
              if(c[13]==1){
                cnt--;
              }
              c[13]=1;continue;
            }
        }
        if(b[0]=='D'){
           if(b[1]=='A')
            {cnt++;
              if(d[1]==1){
                cnt--;
              }
              d[1]=1;continue;
            }
           if(b[1]=='2')
            {cnt++;
              if(d[2]==1){
                cnt--;
              }
              d[2]=1;continue;
            }
           if(b[1]=='3')
            {cnt++;
              if(d[3]==1){
                cnt--;
              }
              d[3]=1;continue;
            }
           if(b[1]=='4')
            {cnt++;
              if(d[4]==1){
                cnt--;
              }
              d[4]=1;continue;
            }
           if(b[1]=='5')
            {cnt++;
              if(d[5]==1){
                cnt--;
              }
              d[5]=1;continue;
            }
           if(b[1]=='6')
            {cnt++;
              if(d[6]==1){
                cnt--;
              }
              d[6]=1;continue;
            }
           if(b[1]=='7')
            {cnt++;
              if(d[7]==1){
                cnt--;
              }
              d[7]=1;continue;
            }
           if(b[1]=='8')
            {cnt++;
              if(d[8]==1){
                cnt--;
              }
              d[8]=1;continue;
            }
           if(b[1]=='9')
            {cnt++;
              if(d[9]==1){
                cnt--;
              }
              d[9]=1;continue;
            }
           if(b[1]=='T')
            {cnt++;
              if(d[10]==1){
                cnt--;
              }
              d[10]=1;continue;
            }
           if(b[1]=='J')
            {cnt++;
              if(d[11]==1){
                cnt--;
              }
              d[11]=1;continue;
            }
           if(b[1]=='Q')
            {cnt++;
              if(d[12]==1){
                cnt--;
              }
              d[12]=1;continue;
            }
           if(b[1]=='K')
            {cnt++;
              if(d[13]==1){
                cnt--;
              }
              d[13]=1;continue;
            }
        }
    }
    cout<<52-cnt;
    return 0;
}
