#include<bits/stdc++.h>
using namespace std;
int n,a[53];
char b[2];
int main(){
    freopen("poker.in","r",stdin);
    freopen("poker.out","w",stdout);
    cin>>n;
    for(int i=1;i<=n;i++){
        cin>>b;
        if(b[0]=='C'){
			if(b[1]=='A'){
				a[1]=1;
			}
            if(b[1]>='1'&&b[1]<='9'){
                a[b[1]-'0']=1;
            }
            if(b[1]=='T'){
                a[10]=1;
            }
            if(b[1]=='J'){
                a[11]=1;
            }
            if(b[1]=='Q'){
                a[12]=1;
            }
            if(b[1]=='K'){
                a[13]=1;
            }
        }
        if(b[0]=='S'){
			if(b[1]=='A'){
				a[14]=1;
			}
            if(b[1]>='1'&&b[1]<='9'){
                a[13+b[1]-'0']=1;
            }
            if(b[1]=='T'){
                a[23]=1;
            }
            if(b[1]=='J'){
                a[24]=1;
            }
            if(b[1]=='Q'){
                a[25]=1;
            }
            if(b[1]=='K'){
                a[26]=1;
            }
        }
        if(b[0]=='H'){
			if(b[1]=='A'){
				a[27]=1;
			}
            if(b[1]>='1'&&b[1]<='9'){
                a[26+b[1]-'0']=1;
            }
            if(b[1]=='T'){
                a[36]=1;
            }
            if(b[1]=='J'){
                a[37]=1;
            }
            if(b[1]=='Q'){
                a[38]=1;
            }
            if(b[1]=='K'){
                a[39]=1;
            }
        }
        if(b[0]=='D'){
			if(b[1]=='A'){
				a[40]=1;
			}
            if(b[1]>='1'&&b[1]<='9'){
                a[39+b[1]-'0']=1;
            }
            if(b[1]=='T'){
                a[49]=1;
            }
            if(b[1]=='J'){
                a[50]=1;
            }
            if(b[1]=='Q'){
                a[51]=1;
            }
            if(b[1]=='K'){
                a[52]=1;
            }
        }
    }
        int cnt=0;
        for(int i=1;i<=52;i++){
            if(a[i]==1){
                cnt++;
            }
		}
        cout<<52-cnt;
        return 0;
}
