#include<bits/stdc++.h>
#define int long long
using namespace std;
string s[53];
map<string,bool>m;
signed main(){
    freopen("poker.in","r",stdin);
    freopen("poker.out","w",stdout);
    int n,sum=0;
    cin>>n;
    for(int i=1;i<=n;i++){
        cin>>s[i];
        m[s[i]]=true;
    }
    if(m["DA"]==false)
        sum++;
    if(m["CA"]==false)
        sum++;
    if(m["HA"]==false)
        sum++;
    if(m["SA"]==false)
        sum++;
    if(m["D2"]==false)
        sum++;
    if(m["C2"]==false)
        sum++;
    if(m["H2"]==false)
        sum++;
    if(m["S2"]==false)
        sum++;
    if(m["D3"]==false)
        sum++;
    if(m["C3"]==false)
        sum++;
    if(m["H3"]==false)
        sum++;
    if(m["S3"]==false)
        sum++;
    if(m["D4"]==false)
        sum++;
    if(m["C4"]==false)
        sum++;
    if(m["H4"]==false)
        sum++;
    if(m["S4"]==false)
        sum++;
    if(m["D5"]==false)
        sum++;
    if(m["C5"]==false)
        sum++;
    if(m["H5"]==false)
        sum++;
    if(m["S5"]==false)
        sum++;
    if(m["D6"]==false)
        sum++;
    if(m["C6"]==false)
        sum++;
    if(m["H6"]==false)
        sum++;
    if(m["S6"]==false)
        sum++;
    if(m["D7"]==false)
        sum++;
    if(m["C7"]==false)
        sum++;
    if(m["H7"]==false)
        sum++;
    if(m["S7"]==false)
        sum++;
    if(m["D8"]==false)
        sum++;
    if(m["C8"]==false)
        sum++;
    if(m["H8"]==false)
        sum++;
    if(m["S8"]==false)
        sum++;
    if(m["D9"]==false)
        sum++;
    if(m["C9"]==false)
        sum++;
    if(m["H9"]==false)
        sum++;
    if(m["S9"]==false)
        sum++;
    if(m["DT"]==false)
        sum++;
    if(m["CT"]==false)
        sum++;
    if(m["HT"]==false)
        sum++;
    if(m["ST"]==false)
        sum++;
    if(m["DJ"]==false)
        sum++;
    if(m["CJ"]==false)
        sum++;
    if(m["HJ"]==false)
        sum++;
    if(m["SJ"]==false)
        sum++;
    if(m["DQ"]==false)
        sum++;
    if(m["CQ"]==false)
        sum++;
    if(m["HQ"]==false)
        sum++;
    if(m["SQ"]==false)
        sum++;
    if(m["DK"]==false)
        sum++;
    if(m["CK"]==false)
        sum++;
    if(m["HK"]==false)
        sum++;
    if(m["SK"]==false)
        sum++;
    cout<<sum;
    return 0;
}