#include <bits/stdc++.h>
using namespace std;
bool d2, d3 ,d4 ,d5 ,d6,d7 ,d8 ,d9 ,dt ,dj ,dq ,dk ,da;
bool c2, c3 ,c4 ,c5 ,c6,c7 ,c8 ,c9 ,ct ,cj ,cq ,ck ,ca;
bool h2, h3 ,h4 ,h5 ,h6,h7 ,h8 ,h9 ,ht ,hj ,hq ,hk ,ha;
bool s2, s3 ,s4 ,s5 ,s6,s7 ,s8 ,s9 ,st ,sj ,sq ,sk ,sa;
int  main (){
    freopen("poker.in","r",stdin);
    freopen("poker.out","w",stdout);
    string a[105];
    int n;
    cin  >> n;
    for(int i=1;i<=n;i++){
        cin >> a[i];
        if(a[i]=="D2"){
            d2=1;
        }
        if(a[i]=="D3"){
            d3=1;
        }
        if(a[i]=="D4"){
            d4=1;
        }
        if(a[i]=="D5"){
            d5=1;
        }
        if(a[i]=="D6"){
            d6=1;
        }
        if(a[i]=="D7"){
            d7=1;
        }
        if(a[i]=="D8"){
            d8=1;
        }
        if(a[i]=="D9"){
            d9=1;
        }
        if(a[i]=="DA"){
            da=1;
        }
        if(a[i]=="DT"){
            dt=1;
        }
        if(a[i]=="DJ"){
            dj=1;
        }
        if(a[i]=="DQ"){
            dq=1;
        }
        if(a[i]=="DK"){
            dk=1;
        }
        if(a[i]=="C2"){
            c2=1;
        }
        if(a[i]=="C3"){
            c3=1;
        }
        if(a[i]=="C4"){
            c4=1;
        }
        if(a[i]=="C5"){
            c5=1;
        }
        if(a[i]=="C6"){
            c6=1;
        }
        if(a[i]=="C7"){
            c7=1;
        }
        if(a[i]=="C8"){
            c8=1;
        }
        if(a[i]=="C9"){
            c9=1;
        }
        if(a[i]=="CA"){
            ca=1;
        }
        if(a[i]=="CT"){
            ct=1;
        }
        if(a[i]=="CJ"){
            cj=1;
        }
        if(a[i]=="CQ"){
            cq=1;
        }
        if(a[i]=="CK"){
            ck=1;
        }
        if(a[i]=="H2"){
            h2=1;
        }
        if(a[i]=="H3"){
            h3=1;
        }
        if(a[i]=="H4"){
            h4=1;
        }
        if(a[i]=="H5"){
            h5=1;
        }
        if(a[i]=="H6"){
            h6=1;
        }
        if(a[i]=="H7"){
            h7=1;
        }
        if(a[i]=="H8"){
            h8=1;
        }
        if(a[i]=="H9"){
            h9=1;
        }
        if(a[i]=="HA"){
            ha=1;
        }
        if(a[i]=="HT"){
            ht=1;
        }
        if(a[i]=="HJ"){
            hj=1;
        }
        if(a[i]=="HQ"){
            hq=1;
        }
        if(a[i]=="HK"){
            hk=1;
        }
        if(a[i]=="S2"){
            s2=1;
        }
        if(a[i]=="S3"){
            s3=1;
        }
        if(a[i]=="S4"){
            s4=1;
        }
        if(a[i]=="S5"){
            s5=1;
        }
        if(a[i]=="S6"){
            s6=1;
        }
        if(a[i]=="S7"){
            s7=1;
        }
        if(a[i]=="S8"){
            s8=1;
        }
        if(a[i]=="S9"){
            s9=1;
        }
        if(a[i]=="SA"){
            sa=1;
        }
        if(a[i]=="ST"){
            st=1;
        }
        if(a[i]=="SJ"){
            sj=1;
        }
        if(a[i]=="SQ"){
            sq=1;
        }
        if(a[i]=="SK"){
            sk=1;
        }
    }
    int ans=0;
    if(!d2){
        ans++;
    }
    if(!d3){
        ans++;
    }
    if(!d4){
        ans++;
    }
    if(!d5){
        ans++;
    }
    if(!d6){
        ans++;
    }
    if(!d7){
        ans++;
    }
    if(!d8){
        ans++;
    }
    if(!d9){
        ans++;
    }
    if(!dt){
        ans++;
    }
    if(!dj){
        ans++;
    }
    if(!dq){
        ans++;
    }
    if(!dk){
        ans++;
    }
    if(!da){
        ans++;
    }
    if(!c2){
        ans++;
    }
    if(!c3){
        ans++;
    }
    if(!c4){
        ans++;
    }
    if(!c5){
        ans++;
    }
    if(!c6){
        ans++;
    }
    if(!c7){
        ans++;
    }
    if(!c8){
        ans++;
    }
    if(!c9){
        ans++;
    }
    if(!ct){
        ans++;
    }
    if(!cj){
        ans++;
    }
    if(!cq){
        ans++;
    }
    if(!ck){
        ans++;
    }
    if(!ca){
        ans++;
    }
    if(!h2){
        ans++;
    }
    if(!h3){
        ans++;
    }
    if(!h4){
        ans++;
    }
    if(!h5){
        ans++;
    }
    if(!h6){
        ans++;
    }
    if(!h7){
        ans++;
    }
    if(!h8){
        ans++;
    }
    if(!h9){
        ans++;
    }
    if(!ht){
        ans++;
    }
    if(!hj){
        ans++;
    }
    if(!hq){
        ans++;
    }
    if(!hk){
        ans++;
    }
    if(!ha){
        ans++;
    }
    if(!s2){
        ans++;
    }
    if(!s3){
        ans++;
    }
    if(!s4){
        ans++;
    }
    if(!s5){
        ans++;
    }
    if(!s6){
        ans++;
    }
    if(!s7){
        ans++;
    }
    if(!s8){
        ans++;
    }
    if(!s9){
        ans++;
    }
    if(!st){
        ans++;
    }
    if(!sj){
        ans++;
    }
    if(!sq){
        ans++;
    }
    if(!sk){
        ans++;
    }
    if(!sa){
        ans++;
    }
    cout <<ans;
    return 0;
}
