#include<bits/stdc++.h>
using namespace std;
int n,i,a[3][101],j,num=0;
string s;
int main(){
    freopen("poker.in","r",stdin);
    freopen("poker.out","w",stdout);
    cin>>n;
    for(i=1;i<=n;i++){
        cin>>s;
        if(s[0]=='D'){
            a[1][i]=1;
        }
        if(s[0]=='C'){
            a[1][i]=2;
        }
        if(s[0]=='H'){
            a[1][i]=3;
        }
        if(s[0]=='S'){
            a[1][i]=4;
        }
        if(s[1]=='A'){
            a[2][i]=1;
        }
        if(s[1]=='T'){
            a[2][i]=10;
        }
        if(s[1]=='J'){
            a[2][i]=11;
        }
        if(s[1]=='Q'){
            a[2][i]=12;
        }
        if(s[1]=='K'){
            a[2][i]=13;
        }
        if(isdigit(s[1])){
            a[2][i]=s[1]-'0';
        }
        for(j=1;j<i;j++){
                if(a[1][i]==a[1][j]&&a[2][i]==a[2][j]&&i!=j){
                    a[1][i]=0;
                    a[2][i]=0;
                    i--;
                    break;
                }
        }
    }
    for(i=1;i<=n;i++){
        if(a[1][i]!=0&&a[2][i]!=0)num++;
    }
    cout<<52-num;
}