#include<iostream>
using namespace std;
int main()
{
    freopen("sticks.in","r",stdin);
    freopen("sticks.out","w",stdout);
    int t;
    cin>>t;
    int n;
    while(t--)
    {
        cin>>n;
        if(n<2)
        {
            cout<<-1<<endl;
            continue;
        }
        if(n%7==0)
        {
            while(n)
            {
                cout<<8;
                n-=7;
            }
            cout<<endl;
            continue;
        }
        if(n%7==1)
        {
            cout<<10;
            n-=8;
            while(n)
            {
                cout<<8;
                n-=7;
            }
            cout<<endl;
            continue;
        }
        if(n%7==2)
        {
            cout<<1;
            n-=2;
            while(n)
            {
                cout<<8;
                n-=7;
            }
            cout<<endl;
            continue;
        }
        if(n==3)
        {
            cout<<7<<endl;
            continue;
        }
        if(n%7==3)
        {
            cout<<23;
            n-=10;
            while(n)
            {
                cout<<8;
                n-=7;
            }
            cout<<endl;
            continue;
        }
        if(n==4)
        {
            cout<<4<<endl;
            continue;
        }
        if(n%7==4)
        {
            cout<<20;
            n-=11;
            while(n)
            {
                cout<<8;
                n-=7;
            }
            cout<<endl;
            continue;
        }
        if(n%7==5)
        {
            cout<<2;
            n-=5;
            while(n)
            {
                cout<<8;
                n-=7;
            }
            cout<<endl;
            continue;
        }
        if(n%7==6)
        {
            cout<<6;
            n-=6;
            while(n)
            {
                cout<<8;
                n-=7;
            }
            cout<<endl;
            continue;
        }
    }
    return 0;
}