#include <bits/stdc++.h>

using namespace std;

int main()
{
    freopen("poker.in","r",stdin);
    freopen("poker.out","w",stdout);
    int n;
   cin >>n;
   int sum = 52;
   string s;
   int p1=0,p2=0,p3=0,p4=0,p5=0,p6=0,p7=0,p8=0,p9=0,p10=0,p11=0,p12=0,p13=0,p14=0,p15=0,p16=0,p17=0,p18=0,p19,p20=0,p21=0,p22=0,p23=0,p24=0,p25=0,p26=0,p27=0,p28=0,p29=0,p30=0,p31=0,p32=0,p33=0,p34=0,p35=0;
   int p36=0,p37=0,p38=0,p39=0,p40=0,p41=0,p42=0,p43=0,p44=0,p45=0,p46=0,p47=0,p48=0,p49=0,p50=0,p51=0,p52=0;
   if(n == 1)
   {
        cin>>s;
       cout<<"51";
       return 0;
   }
    string C;
    string B;
    for(int i = 0;i<n;i++)
    {
        cin >> B;
        C=B;
        if(C=="DA")
        {
            if(p1==0)
                {
                sum--;
                p1=1;
                }
        }
        if(C=="D2")
        {
            if(p2==0)
                {
                sum--;
                p2=1;
                }
        }
        if(C=="D3")
        {
            if(p3==0)
                {
                sum--;
                p3=1;
                }
        }
        if(C=="D4")
        {
            if(p4==0)
                {
                sum--;
                p4=1;
                }
        }
        if(C=="D5")
        {
            if(p5==0)
                {
                sum--;
                p5=1;
                }
        }
        if(C=="D6")
        {
            if(p6==0)
                {
                sum--;
                p6=1;
                }
        }
        if(C=="D7")
        {
            if(p7==0)
                {
                sum--;
                p7=1;
                }
        }
        if(C=="D8")
        {
            if(p8==0)
                {
                sum--;
                p8=1;
                }
        }
        if(C=="D9")
        {
            if(p9==0)
                {
                sum--;
                p9=1;
                }
        }
        if(C=="DT")
        {
            if(p10==0)
                {
                sum--;
                p10=1;
                }
        }
        if(C=="DJ")
        {
            if(p11==0)
                {
                sum--;
                p11=1;
                }
        }
        if(C=="DQ")
        {
            if(p12==0)
                {
                sum--;
                p12=1;
                }
        }
        if(C=="DK")
        {
            if(p13==0)
                {
                sum--;
                p13=1;
                }
        }
        if(C=="CA")
        {
            if(p14==0)
                {
                sum--;
                p14=1;
                }
        }
        if(C=="C2")
        {
            if(p15==0)
                {
                sum--;
                p15=1;
                }
        }
        if(C=="C3")
        {
            if(p16==0)
                {
                sum--;
                p16=1;
                }
        }
        if(C=="C4")
        {
            if(p17==0)
                {
                sum--;
                p17=1;
                }
        }
        if(C=="C5")
        {
            if(p18==0)
                {
                sum--;
                p18=1;
                }
        }
        if(C=="C6")
        {
            if(p19=0)
                {
                sum--;
                p19=1;
                }
        }
        if(C=="C7")
        {
            if(p20==0)
                {
                sum--;
                p20=1;
                }
        }
        if(C=="C8")
        {
            if(p21==0)
                {
                sum--;
                p21=1;
                }
        }
        if(C=="C9")
        {
            if(p22==0)
                {
                sum--;
                p22=1;
                }
        }
        if(C=="CT")
        {
            if(p23==0)
                {
                sum--;
                p23=1;
                }
        }
        if(C=="CJ")
        {
            if(p24==0)
                {
                sum--;
                p24=1;
                }
        }
        if(C=="CQ")
        {
            if(p25==0)
                {
                sum--;
                p25=1;
                }
        }
        if(C=="CK")
        {
            if(p26==0)
                {
                sum--;
                p26=1;
                }
        }
        if(C=="HA")
        {
            if(p27==0)
                {
                sum--;
                p27=1;
                }
        }
        if(C=="H2")
        {
            if(p28==0)
                {
                sum--;
                p28=1;
                }
        }
        if(C=="H3")
        {
            if(p29==0)
                {
                sum--;
                p29=1;
                }
        }
        if(C=="H4")
        {
            if(p30==0)
                {
                sum--;
                p30=1;
                }
        }
        if(C=="H5")
        {
            if(p31==0)
                {
                sum--;
                p31=1;
                }
        }
        if(C=="H6")
        {
            if(p32==0)
                {
                sum--;
                p32=1;
                }
        }
        if(C=="H7")
        {
            if(p33==0)
                {
                sum--;
                p33=1;
                }
        }
        if(C=="H8")
        {
            if(p34==0)
                {
                sum--;
                p34=1;
                }
        }
        if(C=="H9")
        {
            if(p35==0)
                {
                sum--;
                p35=1;
                }
        }
        if(C=="HT")
        {
            if(p36==0)
                {
                sum--;
                p36=1;
                }
        }
        if(C=="HJ")
        {
            if(p37==0)
                {
                sum--;
                p37=1;
                }
        }
        if(C=="HQ")
        {
            if(p38==0)
                {
                sum--;
                p38=1;
                }
        }
        if(C=="HK")
        {
            if(p39==0)
                {
                sum--;
                p39=1;
                }
        }
        if(C=="SA")
        {
            if(p40==0)
                {
                sum--;
                p40=1;
                }
        }
        if(C=="S2")
        {
            if(p41==0)
                {
                sum--;
                p41=1;
                }
        }
        if(C=="S3")
        {
            if(p42==0)
                {
                sum--;
                p42=1;
                }
        }
        if(C=="S4")
        {
            if(p43==0)
                {
                sum--;
                p43=1;
                }
        }
        if(C=="S5")
        {
            if(p44==0)
                {
                sum--;
                p44=1;
                }
        }
        if(C=="S6")
        {
            if(p45==0)
                {
                sum--;
                p45=1;
                }
        }
        if(C=="S7")
        {
            if(p46==0)
                {
                sum--;
                p46=1;
                }
        }
        if(C=="S8")
        {
            if(p47==0)
                {
                sum--;
                p47=1;
                }
        }
        if(C=="S9")
        {
            if(p48==0)
                {
                sum--;
                p48=1;
                }
        }
        if(C=="ST")
        {
            if(p49==0)
                {
                sum--;
                p49=1;
                }
        }
        if(C=="SJ")
        {
            if(p50==0)
                {
                sum--;
                p50=1;
                }
        }
        if(C=="SQ")
        {
            if(p51==0)
                {
                sum--;
                p51=1;
                }
        }
        if(C=="SK")
        {
            if(p52==0)
                {
                sum--;
                p52=1;
                }
        }



    }
    cout << sum;
    return 0;
}
