#include<bits/stdc++.h>
using namespace std;
int main()
{
    freopen("sticks.in","r",stdin);
    freopen("sticks.out","w",stdout);
    int t;
    cin>>t;
    for(int i=1; i<=t; i++)
    {
        int n,ret=0;
        cin>>n;
        if(n<=20)
        {
            ret++;
            if(n==1)
            {
                cout<<-1;
            }
            if(n==2)
            {
                cout<<1;
            }
            if(n==3)
            {
                cout<<7;
            }
            if(n==4)
            {
                cout<<4;
            }
            if(n==5)
            {
                cout<<2;
            }
            if(n==6)
            {
                cout<<6;
            }
            if(n==7)
            {
                cout<<8;
            }
            if(n==8)
            {
                cout<<10;
            }
            if(n==9)
            {
                cout<<18;
            }
            if(n==10)
            {
                cout<<22;
            }
            if(n==11)
            {
                cout<<20;
            }
            if(n==12)
            {
                cout<<28;
            }
            if(n==13)
            {
                cout<<68;
            }
            if(n==14)
            {
                cout<<88;
            }
            if(n==15)
            {
                cout<<108;
            }
            if(n==16)
            {
                cout<<188;
            }
            if(n==17)
            {
                cout<<200;
            }
            if(n==18)
            {
                cout<<208;
            }
            if(n==19)
            {
                cout<<288;
            }
            if(n==20)
            {
                cout<<688;
            }
        }
        if(n%7==0&&ret==0)
        {
            for(int j=1; j<=n/7; j++)
            {
                cout<<8;
            }
        }
        if(n%7==1&&ret==0)
        {
            cout<<10;
            for(int j=1; j<=(n-8)/7;  j++)
            {
                cout<<8;
            }
        }
        if(n%7==2&&ret==0)
        {
            cout<<1;
            for(int j=1; j<=(n-2)/7; j++)
            {
                cout<<8;
            }
        }
        if(n%7==3&&ret==0)
        {
            cout<<200;
            for(int j=1; j<=(n-17)/7; j++)
            {
                cout<<8;
            }
        }
        if(n%7==4&&ret==0)
        {
            cout<<20;
            for(int j=1; j<=(n-11)/7; j++)
            {
                cout<<8;
            }
        }
        if(n%7==5&&ret==0)
        {
            cout<<2;
            for(int j=1; j<=(n-5)/7; j++)
            {
                cout<<8;
            }
        }
        if(n%7==6&&ret==0)
        {
            cout<<6;
            for(int j=1; j<=(n-6)/7; j++)
            {
                cout<<8;
            }
        }
        cout<<endl;
    }
    return 0;
}
