#include<bits/stdc++.h>
using namespace std;
int main(){
    freopen("poker.in","r",stdin);
    freopen("poker.out","w",stdout);
    int n;
    cin>>n;
    string s,t;
    for(int i=0;i<n;++i){
        cin>>s[i]>>t[i];
    }
    int sum=0;
    bool DA=true,D2=true,D3=true,D4=true,D5=true,D6=true,D7=true,D8=true,D9=true,DT=true,DJ=true,DQ=true,DK=true,CA=true,C2=true,C3=true,C4=true,C5=true,C6=true,C7=true,C8=true,C9=true,CT=true,CJ=true,CQ=true,CK=true,HA=true,H2=true,H3=true,H4=true,H5=true,H6=true,H7=true,H8=true,H9=true,HT=true,HJ=true,HQ=true,HK=true,SA=true,S2=true,S3=true,S4=true,S5=true,S6=true,S7=true,S8=true,S9=true,ST=true,SJ=true,SQ=true,SK=true;
    for(int i=0;i<n;++i){
            if(s[i]=='D'&&t[i]=='A'&&DA==true){
                sum++;
                DA=false;
            }
            if(s[i]=='D'&&t[i]=='2'&&D2==true){
                sum++;
                D2=false;
            }
            if(s[i]=='D'&&t[i]=='3'&&D3==true){
                sum++;
                D3=false;
            }
            if(s[i]=='D'&&t[i]=='4'&&D4==true){
                sum++;
                D4=false;
            }
            if(s[i]=='D'&&t[i]=='5'&&D5==true){
                sum++;
                D5=false;
            }
            if(s[i]=='D'&&t[i]=='6'&&D6==true){
                sum++;
                D6=false;
            }
            if(s[i]=='D'&&t[i]=='7'&&D7==true){
                sum++;
                D7=false;
            }
            if(s[i]=='D'&&t[i]=='8'&&D8==true){
                sum++;
                D8=false;
            }
            if(s[i]=='D'&&t[i]=='9'&&D9==true){
                sum++;
                D9=false;
            }
            if(s[i]=='D'&&t[i]=='T'&&DT==true){
                sum++;
                DT=false;
            }
            if(s[i]=='D'&&t[i]=='J'&&DJ==true){
                sum++;
                DJ=false;
            }
            if(s[i]=='D'&&t[i]=='Q'&&DQ==true){
                sum++;
                DQ=false;
            }
            if(s[i]=='D'&&t[i]=='K'&&DK==true){
                sum++;
                DK=false;
            }
            if(s[i]=='C'&&t[i]=='A'&&CA==true){
                sum++;
                CA=false;
            }
            if(s[i]=='C'&&t[i]=='2'&&C2==true){
                sum++;
                C2=false;
            }
            if(s[i]=='C'&&t[i]=='3'&&C3==true){
                sum++;
                C3=false;
            }
            if(s[i]=='C'&&t[i]=='4'&&C4==true){
                sum++;
                C4=false;
            }
            if(s[i]=='C'&&t[i]=='5'&&C5==true){
                sum++;
                C5=false;
            }
            if(s[i]=='C'&&t[i]=='6'&&C6==true){
                sum++;
                C6=false;
            }
            if(s[i]=='C'&&t[i]=='7'&&C7==true){
                sum++;
                C7=false;
            }
            if(s[i]=='C'&&t[i]=='8'&&C8==true){
                sum++;
                C8=false;
            }
            if(s[i]=='C'&&t[i]=='9'&&C9==true){
                sum++;
                C9=false;
            }
            if(s[i]=='C'&&t[i]=='T'&&CT==true){
                sum++;
                CT=false;
            }
            if(s[i]=='C'&&t[i]=='J'&&CJ==true){
                sum++;
                CJ=false;
            }
            if(s[i]=='C'&&t[i]=='Q'&&CQ==true){
                sum++;
                CQ=false;
            }
            if(s[i]=='C'&&t[i]=='K'&&CK==true){
                sum++;
                CK=false;
            }
            if(s[i]=='H'&&t[i]=='A'&&HA==true){
                sum++;
                HA=false;
            }
            if(s[i]=='H'&&t[i]=='2'&&H2==true){
                sum++;
                H2=false;
            }
            if(s[i]=='H'&&t[i]=='3'&&H3==true){
                sum++;
                H3=false;
            }
            if(s[i]=='H'&&t[i]=='4'&&H4==true){
                sum++;
                H4=false;
            }
            if(s[i]=='H'&&t[i]=='5'&&H5==true){
                sum++;
                H5=false;
            }
            if(s[i]=='H'&&t[i]=='6'&&H6==true){
                sum++;
                H6=false;
            }
            if(s[i]=='H'&&t[i]=='7'&&H7==true){
                sum++;
                H7=false;
            }
            if(s[i]=='H'&&t[i]=='8'&&H8==true){
                sum++;
                H8=false;
            }
            if(s[i]=='H'&&t[i]=='9'&&H9==true){
                sum++;
                H9=false;
            }
            if(s[i]=='H'&&t[i]=='T'&&HT==true){
                sum++;
                HT=false;
            }
            if(s[i]=='H'&&t[i]=='J'&&HJ==true){
                sum++;
                HJ=false;
            }
            if(s[i]=='H'&&t[i]=='Q'&&HQ==true){
                sum++;
                HQ=false;
            }
            if(s[i]=='H'&&t[i]=='K'&&HK==true){
                sum++;
                HK=false;
            }
            if(s[i]=='S'&&t[i]=='A'&&SA==true){
                sum++;
                SA=false;
            }
            if(s[i]=='S'&&t[i]=='2'&&S2==true){
                sum++;
                S2=false;
            }
            if(s[i]=='S'&&t[i]=='3'&&S3==true){
                sum++;
                S3=false;
            }
            if(s[i]=='S'&&t[i]=='4'&&S4==true){
                sum++;
                S4=false;
            }
            if(s[i]=='S'&&t[i]=='5'&&S5==true){
                sum++;
                S5=false;
            }
            if(s[i]=='S'&&t[i]=='6'&&S6==true){
                sum++;
                S6=false;
            }
            if(s[i]=='S'&&t[i]=='7'&&S7==true){
                sum++;
                S7=false;
            }
            if(s[i]=='S'&&t[i]=='8'&&S8==true){
                sum++;
                S8=false;
            }
            if(s[i]=='S'&&t[i]=='9'&&S9==true){
                sum++;
                S9=false;
            }
            if(s[i]=='S'&&t[i]=='T'&&ST==true){
                sum++;
                ST=false;
            }
            if(s[i]=='S'&&t[i]=='J'&&SJ==true){
                sum++;
                SJ=false;
            }
            if(s[i]=='S'&&t[i]=='Q'&&SQ==true){
                sum++;
                SQ=false;
            }
            if(s[i]=='S'&&t[i]=='K'&&SK==true){
                sum++;
                SK=false;
            }

    }
    cout<<52-sum;
    return 0;
}
