#include<iostream>
#include<cstdio>
#include<stack>
using namespace std;
int main(){
    freopen("sticks.in","r",stdin);
    freopen("sticks.out","w",stdout);
    int t;
    cin>>t;
    while(t--){
        int n;
        cin>>n;
        if(n<2){
            cout<<-1<<endl;
            continue;
        }
        if(n<7){
            if(n==6){
                cout<<6;
            }
            if(n==5){
                cout<<2;
            }
            if(n==4){
                cout<<3;
            }
            if(n==3){
                cout<<7;
            }
            if(n==2){
                cout<<1;
            }
            cout<<endl;
            continue;
        }
        stack<int> s;
        while(n>=14){
            n-=7;
            s.push(8);
        }
        if(n<=7){
            s.push(8);
        }
        else{
            if(n==8){
                s.push(0);
                s.push(1);
            }
            if(n==9){
                s.push(8);
                s.push(1);
            }
            if(n==10){
                s.push(2);
                s.push(2);
            }
            if(n==11){
                s.push(0);
                s.push(2);
            }
            if(n==12){
                s.push(37);
                s.push(2);
            }
            if(n==13){
                s.push(8);
                s.push(6);
            }
        }
        while(!s.empty()){
            cout<<s.top();
            s.pop();
        }
        cout<<endl;
    }
}
